version: 2

workflows:
  version: 2
  default:
    jobs:
      - ios-build-test
      - spm
      
step-library:
    - &install-dependencies
      run:
        name: Install Dependencies
        command: |
          carthage bootstrap
    
    - &ios-build-test
      run:
        name: Build and Test for iOS
        command: |
          xcodebuild -sdk iphonesimulator -destination 'platform=iOS Simulator,OS=12.2,name=iPhone X' -project MapboxSpeech.xcodeproj -scheme "MapboxSpeech iOS" clean build test
    
    - &macos-build-test
      run:
        name: Build and Test for macOS
        command: |
          xcodebuild -project MapboxSpeech.xcodeproj -scheme "MapboxSpeech Mac" clean build test
    
    - &tvos-build-test
      run:
        name: Build and Test for tvOS
        command: |
          xcodebuild -destination 'platform=tvOS Simulator,OS=12.2,name=Apple TV 4K (at 1080p)' -project MapboxSpeech.xcodeproj -scheme "MapboxSpeech tvOS" clean build test
    
    - &watchos-build
      run:
        name: Build for watchOS
        command: |
          xcodebuild -destination 'platform=watchOS Simulator,OS=5.2,name=Apple Watch Series 3 - 42mm' -project MapboxSpeech.xcodeproj -scheme "MapboxSpeech watchOS" clean build

jobs:
  ios-build-test:
    macos:
      xcode: "10.2.1"
    environment:
      HOMEBREW_NO_AUTO_UPDATE: 0
    steps:
      - checkout
      - *install-dependencies
      - *ios-build-test
      - *macos-build-test
      - *tvos-build-test
      - *watchos-build
  spm:
    macos:
      xcode: "10.2.1"
    steps:
      - checkout
      - run: swift build
