version: 2

workflows:
  version: 2
  default:
    jobs:
      - ios-build-test
      
step-library:
    - &prepare
      run:
        name: Prepare
        command: |
          if [ $(carthage outdated | grep -cF "latest Carthage version") -eq 0 ]; then brew update && brew upgrade carthage; fi
    
    - &install-dependencies
      run:
        name: Install Dependencies
        command: |
          carthage bootstrap --platform ios
    
    - &ios-build-test
      run:
        name: Build and Test
        command: |
          xcodebuild -sdk iphonesimulator -destination 'platform=iOS Simulator,OS=12.1,name=iPhone X' -project MapboxSpeech.xcodeproj -scheme "MapboxSpeech iOS" clean build test

jobs:
  ios-build-test:
    macos:
      xcode: "10.1.0"
    environment:
      HOMEBREW_NO_AUTO_UPDATE: 0
    steps:
      - checkout
      - *prepare
      - *install-dependencies
      - *ios-build-test
